name = "Aeronautics SMP"
author = "MentoskaPraha & Gljue"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d484311e6d6fc3d0f0b403fca2611539e06da3791c061eac26c4a6db26831cf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
