name = "Aeronautics SMP"
author = "MentoskaPraha & Gljue"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8532eef127faacf9bb76150678880980122fa7e3dd85f360ec10cee32c1b9b89"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
