name = "SMP Modpack"
author = "MentoskaPraha & Gljue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72a801e321e422dc785566ec75d302d92a47210dc912a395a0536f291b6fcd67"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
